# Changes here will be overwritten by Copier
_commit: v2.0.5
_src_path: gh:lincc-frameworks/python-project-template
author_email: name@you.com
author_name: Joseph Chevalier
create_example_module: false
custom_install: true
enforce_style:
- pylint
failure_notification:
- email
include_benchmarks: false
include_docs: false
mypy_type_checking: none
package_name: rail_shire
project_license: MIT
project_name: rail_shire
project_organization: LSSTDESC
python_versions:
- '3.10'
- '3.11'
- '3.12'
